#!/usr/bin/env bash
sudo apt update
sudo apt upgrade -y
sudo apt-get install python -y
sudo apt-get install python3-pip -y
sudo apt install -y gunicorn
pip3 install -r requirement.txt
sudo apt-get install nginx -y
sudo apt-get install systenmctl -y
sudo apt-get install ufw -y
sudo systemctl start nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo rm /etc/nginx/sites-available/default
sudo echo -e 'server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /;
    }
}' > /etc/nginx/sites-available/default
gunicorn -w 4 0.0.0.0:8000 'api.hng_api:App'
systemctl restart nginx
